Repository FRONTENDBOOTCAMP-11th/febc11-vanilla-hotsix, pull requests merged in 2024-10, with the labels that each got.

#9 feat: 파일 수정 #3
  test-ksj.txt
Labels: enhancement

#15 Feature13/author/yujin: 작가홈 - 작가 프로필 마크업, Pretendard 폰트 추가
  src/assets/fonts/Pretendard-Light.otf
  src/assets/images/check_white.png
  src/pages/AuthorPage/author.css
  src/pages/AuthorPage/author.js
  src/pages/AuthorPage/index.html
  src/pages/AuthorPage/main.css
  src/pages/AuthorPage/main.js
  style.css
Labels: enhancement, feature

#17 feature: header, navbar 컴포넌트 생성
  src/assets/images/nav_home.svg
  src/assets/images/nav_home_now.svg
  src/assets/images/nav_mybox.svg
  src/assets/images/nav_mybox_now.svg
  src/assets/images/nav_search.svg
  src/assets/images/nav_search_now.svg
  src/assets/images/nav_write.svg
  src/assets/images/nav_write_now.svg
  src/assets/images/notification.svg
  src/assets/images/search.svg
  src/components/Navbar/bottomNavbar.js
  src/components/Navbar/topNavbar.js
  src/components/header/header.css
  src/components/header/header.js
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
  src/pages/AuthorPage/author.css
  src/pages/AuthorPage/index.html
  style.css
  vite.config.js
Labels: feature

#18 feature: 작가 홈페이지 마크업 완료, 구독 버튼 컴포넌트 생성
  src/assets/images/ico-check.svg
  src/assets/images/ico-plus.svg
  src/components/header/header.css
  src/components/header/header.js
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
  src/components/subscribe/subscribe.css
  src/components/subscribe/subscribe.js
  src/pages/AuthorPage/author.css
  src/pages/AuthorPage/author.js
  src/pages/AuthorPage/index.html
Labels: P1, feature

#20 feature11/login/juseok
  .DS_Store
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/images/.DS_Store
  src/assets/images/checkbox_checked.png
  src/assets/images/checkbox_unchecked.png
  src/assets/images/login_header.png
  src/pages/LoginPage/index.html
  src/pages/LoginPage/login.css
  style.css
Labels: feature

#22 Feature10/post detail page/jinsu 상세 페이지 마크업 작업 완료.
  src/pages/PostDetailPage/index.html
  src/pages/PostDetailPage/postDetailPage.css
  src/pages/PostDetailPage/postDetailPage.js
Labels: feature

#23 feature: 내 서랍 페이지 마크업 완료
  src/assets/images/icon-next.svg
  src/components/header/header.css
  src/pages/AuthorPage/author.css
  src/pages/MyPage/index.html
  src/pages/MyPage/myPage.css
  src/pages/MyPage/myPage.js
Labels: feature

#24 feature: 메인페이지용 헤더 추가
  src/components/header/header.css
  src/components/header/header.js
Labels: feature

#25 Feature16/글쓰기 페이지 마크업(간단한 JS)/jinsu
  src/assets/images/icon-add_img.svg
  src/assets/images/icon-check_black.svg
  src/assets/images/icon-check_green.svg
  src/assets/images/icon-close.svg
  src/assets/images/icon-hide-keyboard.svg
  src/assets/images/icon-keyboard.svg
  src/assets/images/icon-text-alignment.svg
  src/pages/PostDetailPage/postDetailPage.css
  src/pages/PostWritePage/index.html
  src/pages/PostWritePage/postWrite.css
  src/pages/PostWritePage/postWrite.js
Labels: feature

#31 Feature27/search/juseok: 검색 페이지 마크업 완성 (동작 무시하고 시각적 구현만)
  .DS_Store
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/images/icon-close-grey.svg
  src/pages/SearchPage/index.html
  src/pages/SearchPage/search.css
  style.css
Labels: feature

#30 Feature10/상세페이지 컨텐츠 동적 삽입/jinsu
  src/pages/PostDetailPage/index.html
  src/pages/PostDetailPage/postDetailPage.css
  src/pages/PostDetailPage/postDetailPage.js
Labels: enhancement, feature

#33 Feature32/search article page/juseok: 검색 결과 페이지 '글' 탭 마크업, 리팩토링
  .DS_Store
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/images/button-close-grey.svg
  src/pages/SearchArticlePage/index.html
  src/pages/SearchArticlePage/searchArticle.css
  src/pages/SearchArticlePage/searchArticle.js
Labels: feature

#36 fix: navbar, subscribe 컴포넌트 수정, 이미지 api 분리
  src/api/getImg.js
  src/components/navbar/navbar.css
  src/components/subscribe/subscribe.js
  src/pages/AuthorPage/author.js
  src/pages/AuthorPage/index.html
  vite.config.js
Labels: enhancement, feature

#40 [style, fix]글쓰기 페이지 navbar 삽입, navbar 디자인 변경, 오타 수정
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
  src/pages/PostWritePage/index.html
  src/pages/PostWritePage/postWrite.css
Labels: bug, feature

#41 feature: 검색 결과 페이지 '결과 없음' 마크업
  .DS_Store
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/images/logo-b.svg
  src/pages/SearchNonePage/index.html
  src/pages/SearchNonePage/searchNone.css
  src/pages/SearchNonePage/searchNone.js
  style.css
Labels: feature

#43 [feature] '메인' 페이지 마크업
  src/assets/images/icon-cheering-badge.svg
  src/assets/images/icon-cheering-front.svg
  src/assets/images/icon-double-quotation.svg
  src/assets/images/icon-logo-white.svg
  src/assets/images/icon-right-direction.svg
  src/assets/images/icon-scroll-to-top.svg
  src/assets/images/icon-social-facebook.svg
  src/assets/images/icon-social-instagram.svg
  src/assets/images/icon-social-kakao.svg
  src/assets/images/main-award-book-1.svg
  src/assets/images/main-award-book-2.svg
  src/assets/images/main-award-book-3.svg
  src/assets/images/main-publish-project-title-1.svg
  src/assets/images/main-publish-project-title-2.svg
  src/pages/MainPage/index.html
  src/pages/MainPage/main.css
  style.css
Labels: feature

#49 fix: 빌드 설정
  vite.config.js
Labels: bug

#50 [BUG] 빌드 설정
  vite.config.js
Labels: bug

#51 fix: 빌드 설정 base경로 추가
  vite.config.js
Labels: bug

#52 [FIX] config 파일 base추가
  vite.config.js
Labels: bug

#53 feature: 작가 홈 - api 연동 완료
  api/sample/01.회원/01 회원가입,로그인/일반 회원 로그인(_id=4).bru
  api/sample/01.회원/01 회원가입,로그인/회원 가입.bru
  api/sample/01.회원/04.회원 정보 조회/지정한 회원 정보 조회(모든 속성).bru
  api/sample/05.게시판(QnA, 공지 등)/01.목록 조회/게시물 목록 조회(키워드 검색).bru
  api/sample/05.게시판(QnA, 공지 등)/01.목록 조회/내가 작성한 게시물 목록 조회(QnA).bru
  api/sample/05.게시판(QnA, 공지 등)/01.목록 조회/판매자의 모든 상품 게시물 목록 조회(QnA).bru
  api/sample/05.게시판(QnA, 공지 등)/게시물 등록.bru
  src/api/getImg.js
  src/pages/AuthorPage/author.js
Labels: feature

#55 feature: 글쓰기 페이지 모달 창, post 객체 생성
  src/pages/PostWritePage/index.html
  src/pages/PostWritePage/postWrite.css
  src/pages/PostWritePage/postWrite.js
Labels: feature

#57 Feature45/login page features/juseok: 로그인 페이지 기능 구현, api 연동
  api/sample/environments/openmarket-sample.bru
  src/pages/LoginPage/index.html
  src/pages/LoginPage/login.js
Labels: feature

#62 Feature58: 회원가입 페이지 기능 구현 완료
  .DS_Store
  api/.DS_Store
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/images/IconEyeClosed.svg
  src/pages/LoginPage/login.js
  src/pages/SignupPage/index.html
  src/pages/SignupPage/signup.css
  src/pages/SignupPage/signup.js
Labels: feature

#64 fix: db초기화 재실행
  api/bruno-sample/brunch/02-게시판/북마크 목록 가져오기.bru
  api/bruno-sample/brunch/environments/brunch-dev.bru
  api/dbinit-sample/brunch/data.js
  api/dbinit-sample/brunch/uploadFiles/bear.jpg
  api/dbinit-sample/brunch/uploadFiles/cat.png
  api/dbinit-sample/brunch/uploadFiles/duck.jpg
  api/dbinit-sample/brunch/uploadFiles/flower.jpg
  api/dbinit-sample/brunch/uploadFiles/park.jpg
  api/dbinit-sample/brunch/uploadFiles/white_dog.jpg
Labels: bug, documentation

#65 feature: 내서랍 페이지 API 통신 완료
  index.html
  public/Image.svg
  public/vite.svg
  src/api/getImg.js
  src/pages/AuthorPage/author.css
  src/pages/AuthorPage/author.js
  src/pages/AuthorPage/index.html
  src/pages/MyPage/index.html
  src/pages/MyPage/myPage.css
  src/pages/MyPage/myPage.js
Labels: feature

#72 fix: 배포 환경 설정
  src/components/navbar/navbar.js
Labels: feature

#74 fix: 배포 테스트
  src/components/navbar/navbar.js
Labels: bug

#73 [FIX] 배포 환경설정
  src/components/navbar/navbar.js
Labels: bug

#77 feat: 게시글, 작가 홈 연결
  src/pages/AuthorPage/author.js
  src/pages/MyPage/myPage.css
  src/pages/MyPage/myPage.js
  src/pages/PostDetailPage/postDetailPage.js
Labels: feature

#78 feat: 내서랍 최근 본 게시물
  src/pages/MyPage/myPage.css
  src/pages/MyPage/myPage.js
  src/pages/PostDetailPage/postDetailPage.js
Labels: feature

#80 feature: 헤더 컴포넌트 기능 추가
  src/components/header/header.js
Labels: enhancement, feature

#81 Feature63: 발견 페이지 통합 및 기능 구현, 디렉토리 정리
  .DS_Store
  public/.DS_Store
  public/assets/.DS_Store
  src/.DS_Store
  src/pages/.DS_Store
  src/pages/SearchArticlePage/index.html
  src/pages/SearchArticlePage/searchArticle.css
  src/pages/SearchArticlePage/searchArticle.js
  src/pages/SearchAuthorPage/index.html
  src/pages/SearchAuthorPage/searchAuthor.css
  src/pages/SearchAuthorPage/searchAuthor.js
  src/pages/SearchNonePage/index.html
  src/pages/SearchNonePage/searchNone.css
  src/pages/SearchNonePage/searchNone.js
  src/pages/SearchPage/index.html
  src/pages/SearchPage/search.css
  src/pages/SearchPage/search.js
Labels: documentation, feature

#84 enhancement: 로그인 시 저장되는 정보 추가
  src/pages/LoginPage/index.html
  src/pages/LoginPage/login.css
  src/pages/LoginPage/login.js
Labels: enhancement

#86 feature: 구독 컴포넌트 기능 완성
  src/components/subscribe/subscribe.js
  src/pages/AuthorPage/author.js
  src/pages/MyPage/myPage.js
Labels: feature

#87 feature: 메인 페이지 필수 기능 구현 완료
  public/assets/images/icon-logo-white.svg
  public/assets/images/logo-circle.svg
  public/assets/images/logo-in-book.svg
  src/pages/MainPage/index.html
  src/pages/MainPage/main.css
  src/pages/MainPage/main.js
Labels: enhancement, feature

#92 Bug88/qa/yujin
  src/api/isLogin.js
  src/components/header/header.css
  src/components/header/header.js
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
  src/pages/AuthorPage/author.js
  src/pages/MainPage/main.js
  src/pages/MyPage/myPage.js
  vite.config.js
Labels: bug, enhancement, feature

#93 Feature91/상세 페이지 기능 구현
  public/assets/images/button-comment-submit_clicked.svg
  public/assets/images/button-comment-submit_default.svg
  src/pages/PostPage/detailPage.css
  src/pages/PostPage/detailPage.html
  src/pages/PostPage/detailPage.js
  src/pages/PostPage/writePage.js
Labels: bug, enhancement, feature

#95 Feature82/search page connection: 발견 페이지 필수 기능 구현 완료
  api/bruno-sample/openmarket/environments/openmarket-sample.bru
  src/pages/SearchPage/search.css
  src/pages/SearchPage/search.js
Labels: feature

#97 feature: 헤더 뒤로가기 기능 추가
  public/assets/images/arrow-left.svg
  src/components/header/header.css
  src/components/header/header.js
Labels: bug, enhancement, feature

#98 [enhancement] 로그인 페이지 수정/보완 (1차)
  src/pages/LoginPage/index.html
  src/pages/LoginPage/login.js
Labels: enhancement

#100 feature: QA 반영 1
  src/api/isLogin.js
  src/components/subscribe/subscribe.js
  src/pages/AuthorPage/author.js
  src/pages/MyPage/index.html
  src/pages/MyPage/myPage.css
  src/pages/MyPage/myPage.js
Labels: bug, enhancement, feature

#104 [enhancement] 회원가입 페이지 수정/보완 (1차)
  src/pages/SignupPage/index.html
  src/pages/SignupPage/signup.css
  src/pages/SignupPage/signup.js
Labels: enhancement, feature

#105 [fix] 메인 페이지 및 헤더 수정
  public/assets/images/basic-profile.svg
  src/components/header/header.css
  src/components/header/header.js
  src/pages/MainPage/main.js
Labels: enhancement

#106 Fix102/ 상세페이지 QA
  src/pages/PostPage/detailPage.css
  src/pages/PostPage/detailPage.html
  src/pages/PostPage/detailPage.js
  src/pages/PostPage/writePage.js
Labels: bug, enhancement, feature

#110 feature107: 발견 페이지 수정/보완 완료 (1차)
  api/bruno-sample/openmarket/05.게시판(QnA, 공지 등)/01.목록 조회/게시물 목록 조회.bru
  public/assets/images/seperator-dot.svg
  public/assets/images/seperator-text-by.svg
  src/pages/SearchPage/index.html
  src/pages/SearchPage/search.css
  src/pages/SearchPage/search.js
Labels: enhancement, feature

#113 feature112: 로그인 페이지 수정 보완 (2차)
  src/pages/LoginPage/index.html
  src/pages/LoginPage/login.js
Labels: enhancement, feature

#115 [feature] 로그인, 회원가입 페이지 헤더(뒤로가기) 추가
  src/components/header/header.css
  src/components/header/header.js
  src/pages/LoginPage/index.html
  src/pages/LoginPage/login.css
  src/pages/SignupPage/index.html
  src/pages/SignupPage/signup.css
Labels: feature

#116 [fix] [feature]: 회원가입 페이지 수정보완 (2차)
  src/pages/SignupPage/signup.js
Labels: enhancement, feature

#117 faeture: 회원정보 수정 페이지 및 QA 수정
  api/dbinit-sample/brunch/uploadFiles/basic-profile.svg
  src/api/isLogin.js
  src/components/subscribe/subscribe.js
  src/pages/AuthorPage/author.css
  src/pages/AuthorPage/author.js
  src/pages/AuthorPage/index.html
  src/pages/MyPage/index.html
  src/pages/MyPage/myPage.css
  src/pages/MyPage/myPage.js
  src/pages/MyPage/userInfo.css
  src/pages/MyPage/userInfo.html
  src/pages/MyPage/userInfo.js
  src/pages/PostPage/detailPage.html
  src/pages/PostPage/detailPage.js
  src/pages/SignupPage/signup.js
Labels: feature

#119 fix: 글쓰기 페이지, 상세 페이지 QA
  src/pages/PostPage/detailPage.css
  src/pages/PostPage/detailPage.html
  src/pages/PostPage/detailPage.js
  src/pages/PostPage/writePage.css
  src/pages/PostPage/writePage.html
  src/pages/PostPage/writePage.js
Labels: bug, enhancement, feature

#121 feature: 배포사이트 설정
  netlify.toml
  public/_redirects
  src/components/header/header.css
  vite.config.js
Labels: feature

#123 [fix] 회원가입 페이지 자잘한 수정
  src/pages/SignupPage/signup.js
Labels: bug

#125 [fix] 회원가입 페이지 리다이렉션 오류 수정
  src/pages/SignupPage/signup.js
Labels: bug

#127 fix: netlify 설정 파일 삭제
  netlify.toml
Labels: bug

#129 fix: (발견 페이지) 2차 수정보완 완료
  public/assets/.DS_Store
  src/pages/SearchPage/index.html
  src/pages/SearchPage/search.css
  src/pages/SearchPage/search.js
Labels: enhancement

#131 fix: QA 수정
  api/dbinit-sample/brunch/data.js
  api/dbinit-sample/brunch/uploadFiles/basic-profile.png
  api/dbinit-sample/brunch/uploadFiles/gpt.png
  public/assets/images/camera.svg
  src/pages/MyPage/myPage.js
  src/pages/MyPage/userInfo.css
  src/pages/MyPage/userInfo.js
  src/pages/SignupPage/signup.js
Labels: bug, enhancement

#132 fix128/ 글쓰기, 상세 페이지 QA
  public/assets/images/background-heart.svg
  src/pages/PostPage/detailPage.css
  src/pages/PostPage/detailPage.html
  src/pages/PostPage/detailPage.js
  src/pages/PostPage/writePage.css
Labels: bug, enhancement, feature

#133 feature: 뒤로가기 기능 커스텀
  src/components/header/header.js
Labels: enhancement

#135 fix: 회원정보 변경 이후 상태 업데이트
  src/pages/MyPage/userInfo.js
Labels: bug

#136 fix: 글쓰기 페이지, 상세 페이지 QA
  src/pages/PostPage/detailPage.js
Labels: bug, enhancement

#137 1차 배포 수정
  api/dbinit-sample/brunch/data.js
  api/dbinit-sample/brunch/uploadFiles/basic-profile.png
  api/dbinit-sample/brunch/uploadFiles/gpt.png
  public/assets/.DS_Store
  public/assets/images/background-heart.svg
  public/assets/images/camera.svg
  src/components/header/header.js
  src/pages/MyPage/myPage.js
  src/pages/MyPage/userInfo.css
  src/pages/MyPage/userInfo.js
  src/pages/PostPage/detailPage.css
  src/pages/PostPage/detailPage.html
  src/pages/PostPage/detailPage.js
  src/pages/PostPage/writePage.css
  src/pages/SearchPage/index.html
  src/pages/SearchPage/search.css
  src/pages/SearchPage/search.js
  src/pages/SignupPage/signup.js
Labels: bug, enhancement, feature

#139 fix: QA 수정
  src/pages/MyPage/myPage.js
  src/pages/MyPage/userInfo.css
  src/pages/MyPage/userInfo.html
Labels: bug

#140 fix: 배포용 페이지 헤더 오류 수정
  src/components/header/header.js
Labels: bug
