Repository FRONTENDBOOTCAMP-11th/febc11-vanilla-hotsix, pull requests merged in 2024-11, with the labels that each got.

#141 [fix] 시작하기, 발견 페이지 최종 수정 보완
  src/pages/LoginPage/login.js
  src/pages/SearchPage/index.html
  src/pages/SearchPage/search.js
  src/pages/SignupPage/signup.js
Labels: bug, enhancement, feature

#142 ver 1. 최종 배포
  src/components/header/header.js
  src/pages/LoginPage/login.js
  src/pages/MyPage/myPage.js
  src/pages/MyPage/userInfo.css
  src/pages/MyPage/userInfo.html
  src/pages/SearchPage/index.html
  src/pages/SearchPage/search.js
  src/pages/SignupPage/signup.js
Labels: feature

#144 fix: 배포용 페이지 헤더 수정
  src/components/header/header.js
Labels: bug

#145 ver1. 최종배포
  src/components/header/header.js
Labels: bug

#146 [docs] 리드미 파일 작성
  README.md
Labels: needs review
